Am bdd tests
MaximRaicov/KinetikFinalTask pull request #7
Opened 2019-12-11 16:31 UTC by amiordan

2019-12-11 17:31 UTC, CristianManic commented
please separate this huge PRs in smaller ones divided by business/technical scope

2019-12-11 17:32 UTC, CristianManic requested changes
please separate this huge PRs in smaller ones divided by business/technical scope

2019-12-12 15:24 UTC, CristianManic commented on src/test/java/cucumber_runner/TestRunner.java
> +
remove blank spaces

2019-12-12 15:27 UTC, CristianManic commented on src/test/java/hooks/TestHooks.java
> +    }
no need of this setter, you can do this exactly in before method

2019-12-12 15:29 UTC, CristianManic commented on src/test/java/hooks/TestHooks.java
> +        fileReader = new ConfigFileReader();
this action does not belongs to this method, you can do this when you initiate this

2019-12-12 15:30 UTC, CristianManic commented on src/test/java/hooks/TestHooks.java
> +        webDriver.navigate().to(fileReader.getApplicationUrl());
this should be done in first step from Background in feature file

2019-12-13 08:44 UTC, vdones approved these changes

2019-12-13 10:30 UTC, MaximRaicov approved these changes

2019-12-13 11:36 UTC, merged